<!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
<script type="application/ld+json">
{
  "@context" : "https://schema.org",
  "@type" : "Article",
  "headline" : "{{ $news['article_title'] }}",
  "author" : {
    "@type" : "Organization",
    "name" : "The Fitzwilliam Museum"
  },
  "datePublished" : "{{ $news['publication_date'] }}",
  @if(isset($news['modified_on']))
    "dateModified" : "{{ $news['modified_on'] }}",
  @endif
  @if(isset($news['field_image']))
    "image" : "{{ $news['field_image']['data']['full_url'] }}",
  @else
    "image" : "{{ env('MISSING_IMAGE_URL') }}",
  @endif
  "articleBody" : "{{ $news['article_body'] }}",
  "url" : "{{ Request::url() }}",
  "mainEntityOfPage": {
         "@type": "WebPage",
         "@id": "{{ Request::url() }}"
      },
  "publisher" : {
    "@type" : "Organization",
    "name" : "The University of Cambridge",
    "logo":{
      "@type":"ImageObject",
      "url":"https://fitzmuseum.cam.ac.uk/images/logos/FV.png"
    }
  }
}
</script>
