@extends('layouts.layout')
@section('title', 'Explore our collection')
@section('hero_image',env('CONTENT_STORE') . 'DISCOVER%20OUR%20COLLECTION%20(FINAL).png')
@section('hero_image_title', 'Man and woman looking at paiting in the museum.')
@section('description','A search page for our highlight objects')
@section('keywords', 'search,highlights, objects')
@section('collection-parallax', env('CONTENT_STORE') . 'DISCOVER%20OUR%20COLLECTION%20(FINAL).png')
@include('includes.structure.collections-search-form')
@include('includes.structure.theme-carousel')
@include('includes.structure.period-carousel')
@include('includes.structure.context-carousel')
@include('includes.structure.developer')
