name: Check site for broken links
on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:
    tags:
        description: 'Run checker manually'
jobs:
  check-site-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: harrisonpim/broken-link-checker@0.1.2
        with:
          sitemap: https://fitzmuseum.cam.ac.uk/sitemap.xml
