name: Check site for broken links
on:
  schedule:
    - cron: "0 0 * * 0"
    # every Sunday at midnight
    # see https://crontab.guru/#0_0_*_*_0
  workflow_dispatch: 
    inputs: 
      logLevel: 
        default: warning
        description: "Log level"
        required: true
      tags: 
       description: 'Run manually'
jobs:
  check-site-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - uses: harrisonpim/broken-link-checker@0.2.1
        with:
          sitemap: https://fitzmuseum.cam.ac.uk/sitemap.xml
          allowList: https://tickets.museums.cam.ac.uk/account/create"
